#!/bin/bash
echo "The sum of WATER (${WATER}) and STIR (${STIR}) is $(echo "ibase=water; ${WATER}" | bc) + $(echo "ibase=stir; ${STIR}" | bc) | bc | xargs echo "obase=bestchol; " | bc) in base bestchol."
